from app.doc_generation.processors.abstract_template import AbstractDocumentProcessor
from app.doc_generation.processors.docx_template import DocxDocumentProcessor
from app.doc_generation.processors.html_template import HtmlDocumentProcessor
from app.doc_generation.processors.pdf_template import PdfDocumentProcessor
