apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.environment_file }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config_map.data | nindent 2 }}
