apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-{{ .Values.app_name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.environment }}-{{ .Values.app_name }}
